from .curators import curators_bp
from .students import students_bp
from .groups import groups_bp
from .specializations import specs_bp
from .qualifications import quals_bp
from .roles import roles_bp
from .parents import parents_bp
from .student_parents import student_parents_bp
from .social_statuses import statuses_bp
from .posts import posts_bp
from .hobbies import hobbies_bp
from .import_data import import_bp